spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    enabled: true
    cache: true
    suffix: .html
    prefix: classpath:/templates/

  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name:
    druid:
      filters: stat
      max-active: 1000
      init

# mybatis配置
mybatis:
  mapper-locations: classpath*:com/miaosha/base/mapping/*.xml
  configuration:
    default-statement-timeout: 3000
    default-fetch-size: 100
    map-underscore-to-camel-case: true
  type-aliases-package: com.miaosha.base.vo


server:
  port: 8099
  servlet:
    context-path: /

logging:
  config: classpath:log4j2.yml
