spring:
#  thymeleaf:
#    mode: LEGACYHTML5
#    encoding: utf-8
#    enabled: true
#    cache: true
#    suffix: .html
#    prefix: classpath:/pages/

  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    # druid 数据源配置
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true

      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙
      filters: stat,wall,log4j2

      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true

      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #ip白名单
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #ip黑名单
        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true

  # redis
  redis:
    host: 192.168.100.100
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 100
    password: 123456

#  # static
#  resources:
#    static-locations: classpath:/static/
#    chain:
#      cache: true
#      compressed: true
#      html-application-cache: true
#      enabled: true

  # rabbitmq
#  rabbitmq:
#    host: 192.168.100.133
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    listener:
#      simple:
#        # 消费者数量
#        concurrency: 10
#        max-concurrency: 10
#        # 消费者每次从队列获取的消息数量
#        prefetch: 1
#        # 消费者自动启动
#        auto-startup: true
#        # 消费失败，自动重新入队
#        default-requeue-rejected: true
#    template:
#      retry:
#        # 启用发送重试
#        enabled: true
#        initial-interval: 1000
#        max-attempts: 3
#        max-interval: 10000
#        multiplier: 1.0

# mybatis配置
mybatis:
  mapper-locations: classpath*:com/miaosha/base/mapping/*.xml
  configuration:
    default-statement-timeout: 3000
    default-fetch-size: 100
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.base.vo

server:
  port: 8099
  servlet:
    context-path: /

logging:
  config: classpath:log4j2.yml
